<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <CopyToMotionsFolder>true</CopyToMotionsFolder>
        <CustomContentFolders>PythonEnv</CustomContentFolders>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Luster.TaskFlow.Motion\Luster.TaskFlow.Motion.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Luster.Prism" />
        <PackageReference Include="MinVer" />
        <Reference Include="System.ComponentModel.DataAnnotations" />
        <PackageReference Include="pythonnet"/>
    </ItemGroup>

</Project>
