<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HandyControl" />
        <PackageReference Include="LiveCharts.Wpf" />
        <PackageReference Include="Luster.Prism" />
        <PackageReference Include="MinVer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Luster.Motion.CommonUI\Luster.Motion.CommonUI.csproj" />
    </ItemGroup>

</Project>
