//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luster.SimDevice.SubSystem.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luster.SimDevice.SubSystem.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 2.5D 深度图 的本地化字符串。
        /// </summary>
        public static string _2_5DDepthMap {
            get {
                return ResourceManager.GetString("2.5DDepthMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2D 轮廓图 的本地化字符串。
        /// </summary>
        public static string _2DSkeletonMap {
            get {
                return ResourceManager.GetString("2DSkeletonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动 的本地化字符串。
        /// </summary>
        public static string AbsoluteMove {
            get {
                return ResourceManager.GetString("AbsoluteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速度(mm²) 的本地化字符串。
        /// </summary>
        public static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速(mm/s²) 的本地化字符串。
        /// </summary>
        public static string AccSpeed {
            get {
                return ResourceManager.GetString("AccSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作配置 的本地化字符串。
        /// </summary>
        public static string ActionArea {
            get {
                return ResourceManager.GetString("ActionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作名称 的本地化字符串。
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作类型 的本地化字符串。
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加地址 的本地化字符串。
        /// </summary>
        public static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址数量 的本地化字符串。
        /// </summary>
        public static string AddressCount {
            get {
                return ResourceManager.GetString("AddressCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址描述 的本地化字符串。
        /// </summary>
        public static string AddressDescription {
            get {
                return ResourceManager.GetString("AddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址列表 的本地化字符串。
        /// </summary>
        public static string AddressList {
            get {
                return ResourceManager.GetString("AddressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警代码 的本地化字符串。
        /// </summary>
        public static string AlarmCode {
            get {
                return ResourceManager.GetString("AlarmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警配置 的本地化字符串。
        /// </summary>
        public static string AlarmConfig {
            get {
                return ResourceManager.GetString("AlarmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义报警配置 的本地化字符串。
        /// </summary>
        public static string AlarmConfigCustom {
            get {
                return ResourceManager.GetString("AlarmConfigCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟输入 的本地化字符串。
        /// </summary>
        public static string AnalogIn {
            get {
                return ResourceManager.GetString("AnalogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟量输入输出 的本地化字符串。
        /// </summary>
        public static string AnalogIO {
            get {
                return ResourceManager.GetString("AnalogIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟输出 的本地化字符串。
        /// </summary>
        public static string AnalogOut {
            get {
                return ResourceManager.GetString("AnalogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动扫描 的本地化字符串。
        /// </summary>
        public static string AutoScan {
            get {
                return ResourceManager.GetString("AutoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴 的本地化字符串。
        /// </summary>
        public static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴1 的本地化字符串。
        /// </summary>
        public static string Axis1 {
            get {
                return ResourceManager.GetString("Axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴数量 的本地化字符串。
        /// </summary>
        public static string AxisCount {
            get {
                return ResourceManager.GetString("AxisCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正方向 的本地化字符串。
        /// </summary>
        public static string AxisForward {
            get {
                return ResourceManager.GetString("AxisForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴点位调试 的本地化字符串。
        /// </summary>
        public static string AxisIODebug {
            get {
                return ResourceManager.GetString("AxisIODebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴运动前提 的本地化字符串。
        /// </summary>
        public static string AxisMotionPremise {
            get {
                return ResourceManager.GetString("AxisMotionPremise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴号 的本地化字符串。
        /// </summary>
        public static string AxisNo {
            get {
                return ResourceManager.GetString("AxisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 型号 的本地化字符串。
        /// </summary>
        public static string AxisPML {
            get {
                return ResourceManager.GetString("AxisPML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴点位配置 的本地化字符串。
        /// </summary>
        public static string AxisPosConfig {
            get {
                return ResourceManager.GetString("AxisPosConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string AxisPosition {
            get {
                return ResourceManager.GetString("AxisPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴类型 的本地化字符串。
        /// </summary>
        public static string AxisType {
            get {
                return ResourceManager.GetString("AxisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入 的本地化字符串。
        /// </summary>
        public static string BatchImport {
            get {
                return ResourceManager.GetString("BatchImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行为 的本地化字符串。
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吹 的本地化字符串。
        /// </summary>
        public static string Blow {
            get {
                return ResourceManager.GetString("Blow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吹/关 的本地化字符串。
        /// </summary>
        public static string BlowClose {
            get {
                return ResourceManager.GetString("BlowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吹DO 的本地化字符串。
        /// </summary>
        public static string BlowDO {
            get {
                return ResourceManager.GetString("BlowDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂商 的本地化字符串。
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮灯 的本地化字符串。
        /// </summary>
        public static string ButtonLight {
            get {
                return ResourceManager.GetString("ButtonLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机配置 的本地化字符串。
        /// </summary>
        public static string CameraConfigutation {
            get {
                return ResourceManager.GetString("CameraConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机窗口 的本地化字符串。
        /// </summary>
        public static string CameraWindow {
            get {
                return ResourceManager.GetString("CameraWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道 的本地化字符串。
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道数 的本地化字符串。
        /// </summary>
        public static string ChannelCount {
            get {
                return ResourceManager.GetString("ChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点检记录 的本地化字符串。
        /// </summary>
        public static string CheckRecord {
            get {
                return ResourceManager.GetString("CheckRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点检结果 的本地化字符串。
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点检时间 的本地化字符串。
        /// </summary>
        public static string CheckTime {
            get {
                return ResourceManager.GetString("CheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一圈移动量 的本地化字符串。
        /// </summary>
        public static string CircleDisplacement {
            get {
                return ResourceManager.GetString("CircleDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清零 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清错 的本地化字符串。
        /// </summary>
        public static string ClearError {
            get {
                return ResourceManager.GetString("ClearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集行数 的本地化字符串。
        /// </summary>
        public static string CollectRows {
            get {
                return ResourceManager.GetString("CollectRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口名称 的本地化字符串。
        /// </summary>
        public static string Comm {
            get {
                return ResourceManager.GetString("Comm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令脉冲 的本地化字符串。
        /// </summary>
        public static string CommandPulse {
            get {
                return ResourceManager.GetString("CommandPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信方式 的本地化字符串。
        /// </summary>
        public static string CommType {
            get {
                return ResourceManager.GetString("CommType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯地址 的本地化字符串。
        /// </summary>
        public static string Communcation {
            get {
                return ResourceManager.GetString("Communcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯行为 的本地化字符串。
        /// </summary>
        public static string CommuncationAction {
            get {
                return ResourceManager.GetString("CommuncationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯地址 的本地化字符串。
        /// </summary>
        public static string CommuncationAddress {
            get {
                return ResourceManager.GetString("CommuncationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信调试 的本地化字符串。
        /// </summary>
        public static string CommuncationTest {
            get {
                return ResourceManager.GetString("CommuncationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯方式 的本地化字符串。
        /// </summary>
        public static string CommuncationType {
            get {
                return ResourceManager.GetString("CommuncationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续发送 的本地化字符串。
        /// </summary>
        public static string ContinuousSend {
            get {
                return ResourceManager.GetString("ContinuousSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标系 的本地化字符串。
        /// </summary>
        public static string CoordinateSystem {
            get {
                return ResourceManager.GetString("CoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建ROI 的本地化字符串。
        /// </summary>
        public static string CreateROI {
            get {
                return ResourceManager.GetString("CreateROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置 的本地化字符串。
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前里程 的本地化字符串。
        /// </summary>
        public static string CurrentScale {
            get {
                return ResourceManager.GetString("CurrentScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前值 的本地化字符串。
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸类型 的本地化字符串。
        /// </summary>
        public static string CylinderType {
            get {
                return ResourceManager.GetString("CylinderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据触发 的本地化字符串。
        /// </summary>
        public static string DataTrigger {
            get {
                return ResourceManager.GetString("DataTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据值 的本地化字符串。
        /// </summary>
        public static string DataValue {
            get {
                return ResourceManager.GetString("DataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减速度(mm²) 的本地化字符串。
        /// </summary>
        public static string Dcc {
            get {
                return ResourceManager.GetString("Dcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减速(mm/s²) 的本地化字符串。
        /// </summary>
        public static string DccSpeed {
            get {
                return ResourceManager.GetString("DccSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟(ms) 的本地化字符串。
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检知 的本地化字符串。
        /// </summary>
        public static string Detector {
            get {
                return ResourceManager.GetString("Detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件设备 的本地化字符串。
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备列表 的本地化字符串。
        /// </summary>
        public static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        public static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离(mm) 的本地化字符串。
        /// </summary>
        public static string Diatance {
            get {
                return ResourceManager.GetString("Diatance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字输入 的本地化字符串。
        /// </summary>
        public static string DigitalIn {
            get {
                return ResourceManager.GetString("DigitalIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字量输入输出 的本地化字符串。
        /// </summary>
        public static string DigitalIO {
            get {
                return ResourceManager.GetString("DigitalIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字输出 的本地化字符串。
        /// </summary>
        public static string DigitalOut {
            get {
                return ResourceManager.GetString("DigitalOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去使能 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示类型 的本地化字符串。
        /// </summary>
        public static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双控 的本地化字符串。
        /// </summary>
        public static string DoubleControl {
            get {
                return ResourceManager.GetString("DoubleControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去使能 的本地化字符串。
        /// </summary>
        public static string DownEnable {
            get {
                return ResourceManager.GetString("DownEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽 的本地化字符串。
        /// </summary>
        public static string Drag {
            get {
                return ResourceManager.GetString("Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第八个 IO 的本地化字符串。
        /// </summary>
        public static string EighthIO {
            get {
                return ResourceManager.GetString("EighthIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 急停 的本地化字符串。
        /// </summary>
        public static string EmergencyStop {
            get {
                return ResourceManager.GetString("EmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使能 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器通道号 的本地化字符串。
        /// </summary>
        public static string EncoderNo {
            get {
                return ResourceManager.GetString("EncoderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器类型 的本地化字符串。
        /// </summary>
        public static string EncoderType {
            get {
                return ResourceManager.GetString("EncoderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节顺序 的本地化字符串。
        /// </summary>
        public static string EndianType {
            get {
                return ResourceManager.GetString("EndianType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文件 的本地化字符串。
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到文本 的本地化字符串。
        /// </summary>
        public static string ExportToTxt {
            get {
                return ResourceManager.GetString("ExportToTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        public static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出 的本地化字符串。
        /// </summary>
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出检知 的本地化字符串。
        /// </summary>
        public static string ExtendDetetor {
            get {
                return ResourceManager.GetString("ExtendDetetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出DI 的本地化字符串。
        /// </summary>
        public static string ExtendDI {
            get {
                return ResourceManager.GetString("ExtendDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出DO 的本地化字符串。
        /// </summary>
        public static string ExtendDO {
            get {
                return ResourceManager.GetString("ExtendDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出名称 的本地化字符串。
        /// </summary>
        public static string ExtendName {
            get {
                return ResourceManager.GetString("ExtendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出状态 的本地化字符串。
        /// </summary>
        public static string ExtendStatus {
            get {
                return ResourceManager.GetString("ExtendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第五个 IO 的本地化字符串。
        /// </summary>
        public static string FifthIO {
            get {
                return ResourceManager.GetString("FifthIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴1 的本地化字符串。
        /// </summary>
        public static string FirstAxis {
            get {
                return ResourceManager.GetString("FirstAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一个 IO 的本地化字符串。
        /// </summary>
        public static string FirstIO {
            get {
                return ResourceManager.GetString("FirstIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞拍模块 的本地化字符串。
        /// </summary>
        public static string FlyingPhoto {
            get {
                return ResourceManager.GetString("FlyingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞拍模块名称 的本地化字符串。
        /// </summary>
        public static string FlyingPhotoName {
            get {
                return ResourceManager.GetString("FlyingPhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正行程 的本地化字符串。
        /// </summary>
        public static string ForwardTrip {
            get {
                return ResourceManager.GetString("ForwardTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴4 的本地化字符串。
        /// </summary>
        public static string FourthAxis {
            get {
                return ResourceManager.GetString("FourthAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第四个 IO 的本地化字符串。
        /// </summary>
        public static string FourthIO {
            get {
                return ResourceManager.GetString("FourthIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧率 的本地化字符串。
        /// </summary>
        public static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率(ms) 的本地化字符串。
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 齿轮比分母 的本地化字符串。
        /// </summary>
        public static string GearRatioDenominator {
            get {
                return ResourceManager.GetString("GearRatioDenominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 齿轮比分子 的本地化字符串。
        /// </summary>
        public static string GearRatioNumerator {
            get {
                return ResourceManager.GetString("GearRatioNumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取流 的本地化字符串。
        /// </summary>
        public static string Grab {
            get {
                return ResourceManager.GetString("Grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用变速箱 的本地化字符串。
        /// </summary>
        public static string HaveTransmission {
            get {
                return ResourceManager.GetString("HaveTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零高速 的本地化字符串。
        /// </summary>
        public static string HighSpeed {
            get {
                return ResourceManager.GetString("HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零设备 的本地化字符串。
        /// </summary>
        public static string HomeDevice {
            get {
                return ResourceManager.GetString("HomeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零参数 的本地化字符串。
        /// </summary>
        public static string HomeParas {
            get {
                return ResourceManager.GetString("HomeParas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零类型 的本地化字符串。
        /// </summary>
        public static string HomeType {
            get {
                return ResourceManager.GetString("HomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零 的本地化字符串。
        /// </summary>
        public static string HomeZero {
            get {
                return ResourceManager.GetString("HomeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入PLC地址 的本地化字符串。
        /// </summary>
        public static string ImportPlcAddress {
            get {
                return ResourceManager.GetString("ImportPlcAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出状态 的本地化字符串。
        /// </summary>
        public static string InExtendName {
            get {
                return ResourceManager.GetString("InExtendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入IO 名称 的本地化字符串。
        /// </summary>
        public static string InIOName {
            get {
                return ResourceManager.GetString("InIOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Inport {
            get {
                return ResourceManager.GetString("Inport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回状态 的本地化字符串。
        /// </summary>
        public static string InRetractName {
            get {
                return ResourceManager.GetString("InRetractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰度图 的本地化字符串。
        /// </summary>
        public static string IntensityImage {
            get {
                return ResourceManager.GetString("IntensityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO 数量 的本地化字符串。
        /// </summary>
        public static string IOCount {
            get {
                return ResourceManager.GetString("IOCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO监控 的本地化字符串。
        /// </summary>
        public static string IOMontor {
            get {
                return ResourceManager.GetString("IOMontor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO名称 的本地化字符串。
        /// </summary>
        public static string IOName {
            get {
                return ResourceManager.GetString("IOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO类型 的本地化字符串。
        /// </summary>
        public static string IOType {
            get {
                return ResourceManager.GetString("IOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 地址 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JOG 的本地化字符串。
        /// </summary>
        public static string Jog {
            get {
                return ResourceManager.GetString("Jog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jog速度 的本地化字符串。
        /// </summary>
        public static string JogSpped {
            get {
                return ResourceManager.GetString("JogSpped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门型轨迹 的本地化字符串。
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键参数配置 的本地化字符串。
        /// </summary>
        public static string KeyParameterConfig {
            get {
                return ResourceManager.GetString("KeyParameterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找类似 {0} 的本地化字符串。 的本地化字符串。
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光配置 的本地化字符串。
        /// </summary>
        public static string LaserConfigutation {
            get {
                return ResourceManager.GetString("LaserConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线扫配置文件地址 的本地化字符串。
        /// </summary>
        public static string LaserConfigutationPath {
            get {
                return ResourceManager.GetString("LaserConfigutationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光数据触发模式 的本地化字符串。
        /// </summary>
        public static string LaserDataTriggerTip {
            get {
                return ResourceManager.GetString("LaserDataTriggerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光硬触发配置 的本地化字符串。
        /// </summary>
        public static string LaserHardTrrigerConfigutation {
            get {
                return ResourceManager.GetString("LaserHardTrrigerConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光 Job 的本地化字符串。
        /// </summary>
        public static string LaserJob {
            get {
                return ResourceManager.GetString("LaserJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光名称 的本地化字符串。
        /// </summary>
        public static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光开始触发IO  的本地化字符串。
        /// </summary>
        public static string LaserStartIO {
            get {
                return ResourceManager.GetString("LaserStartIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光开始触发模式 的本地化字符串。
        /// </summary>
        public static string LaserStartTip {
            get {
                return ResourceManager.GetString("LaserStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次月保养时间 的本地化字符串。
        /// </summary>
        public static string LastMonthMaintenance {
            get {
                return ResourceManager.GetString("LastMonthMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次周保养时间 的本地化字符串。
        /// </summary>
        public static string LastWeekMaintenance {
            get {
                return ResourceManager.GetString("LastWeekMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁存通道 的本地化字符串。
        /// </summary>
        public static string LCTNo {
            get {
                return ResourceManager.GetString("LCTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源配置 的本地化字符串。
        /// </summary>
        public static string LightConfigutation {
            get {
                return ResourceManager.GetString("LightConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源控制器 的本地化字符串。
        /// </summary>
        public static string LightController {
            get {
                return ResourceManager.GetString("LightController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源熄灭延迟时间(ms) 的本地化字符串。
        /// </summary>
        public static string LightDelayToOff {
            get {
                return ResourceManager.GetString("LightDelayToOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线性插补 的本地化字符串。
        /// </summary>
        public static string LinearComplement {
            get {
                return ResourceManager.GetString("LinearComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线激光 的本地化字符串。
        /// </summary>
        public static string LineLaser {
            get {
                return ResourceManager.GetString("LineLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载配置 的本地化字符串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位区间(mm) 的本地化字符串。
        /// </summary>
        public static string LocationRange {
            get {
                return ResourceManager.GetString("LocationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回零低速 的本地化字符串。
        /// </summary>
        public static string LowSpeed {
            get {
                return ResourceManager.GetString("LowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备保养 的本地化字符串。
        /// </summary>
        public static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护里程 的本地化字符串。
        /// </summary>
        public static string MaintainScale {
            get {
                return ResourceManager.GetString("MaintainScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保养 的本地化字符串。
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮廓图或者深度图 的本地化字符串。
        /// </summary>
        public static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配 的本地化字符串。
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大位置 的本地化字符串。
        /// </summary>
        public static string MaxPosition {
            get {
                return ResourceManager.GetString("MaxPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大行程(单位 mm) 的本地化字符串。
        /// </summary>
        public static string MaxPositionWithUnit {
            get {
                return ResourceManager.GetString("MaxPositionWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大里程 的本地化字符串。
        /// </summary>
        public static string MaxScale {
            get {
                return ResourceManager.GetString("MaxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小位置 的本地化字符串。
        /// </summary>
        public static string MinPosition {
            get {
                return ResourceManager.GetString("MinPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小行程(单位 mm) 的本地化字符串。
        /// </summary>
        public static string MinPositionWithUnit {
            get {
                return ResourceManager.GetString("MinPositionWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModbusRTU 的本地化字符串。
        /// </summary>
        public static string ModbusRTU {
            get {
                return ResourceManager.GetString("ModbusRTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块配置 的本地化字符串。
        /// </summary>
        public static string ModuleConfig {
            get {
                return ResourceManager.GetString("ModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组名称 的本地化字符串。
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组或者名称 的本地化字符串。
        /// </summary>
        public static string ModuleOrName {
            get {
                return ResourceManager.GetString("ModuleOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控设备 的本地化字符串。
        /// </summary>
        public static string MonitorDevice {
            get {
                return ResourceManager.GetString("MonitorDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控值 的本地化字符串。
        /// </summary>
        public static string MonitorValue {
            get {
                return ResourceManager.GetString("MonitorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制卡 的本地化字符串。
        /// </summary>
        public static string MotionCard {
            get {
                return ResourceManager.GetString("MotionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动前提 的本地化字符串。
        /// </summary>
        public static string MotionPremise {
            get {
                return ResourceManager.GetString("MotionPremise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动调试 的本地化字符串。
        /// </summary>
        public static string MotionTest {
            get {
                return ResourceManager.GetString("MotionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动距离 的本地化字符串。
        /// </summary>
        public static string MoveDistance {
            get {
                return ResourceManager.GetString("MoveDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动前提 的本地化字符串。
        /// </summary>
        public static string MovePrecondition {
            get {
                return ResourceManager.GetString("MovePrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动类型 的本地化字符串。
        /// </summary>
        public static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否检知 的本地化字符串。
        /// </summary>
        public static string NeedDetetor {
            get {
                return ResourceManager.GetString("NeedDetetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否回零 的本地化字符串。
        /// </summary>
        public static string NeedHome {
            get {
                return ResourceManager.GetString("NeedHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否屏蔽 的本地化字符串。
        /// </summary>
        public static string NeedShield {
            get {
                return ResourceManager.GetString("NeedShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负行程 的本地化字符串。
        /// </summary>
        public static string NegativeTrip {
            get {
                return ResourceManager.GetString("NegativeTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一指令 的本地化字符串。
        /// </summary>
        public static string NextCommand {
            get {
                return ResourceManager.GetString("NextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规参数 的本地化字符串。
        /// </summary>
        public static string NormalParas {
            get {
                return ResourceManager.GetString("NormalParas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空字符 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线配置 的本地化字符串。
        /// </summary>
        public static string OfflineConfigutation {
            get {
                return ResourceManager.GetString("OfflineConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线图片 的本地化字符串。
        /// </summary>
        public static string OfflineImage {
            get {
                return ResourceManager.GetString("OfflineImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线点云 的本地化字符串。
        /// </summary>
        public static string OfflinePointCloud {
            get {
                return ResourceManager.GetString("OfflinePointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他配置 的本地化字符串。
        /// </summary>
        public static string OtherConfigutation {
            get {
                return ResourceManager.GetString("OtherConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 IO 名称 的本地化字符串。
        /// </summary>
        public static string OutIOName {
            get {
                return ResourceManager.GetString("OutIOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令报文 的本地化字符串。
        /// </summary>
        public static string PacketData {
            get {
                return ResourceManager.GetString("PacketData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇偶校验位 的本地化字符串。
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单页数量 的本地化字符串。
        /// </summary>
        public static string PerPageCount {
            get {
                return ResourceManager.GetString("PerPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到位时间 的本地化字符串。
        /// </summary>
        public static string PlaceTime {
            get {
                return ResourceManager.GetString("PlaceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC地址 的本地化字符串。
        /// </summary>
        public static string PlcAddress {
            get {
                return ResourceManager.GetString("PlcAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入轴名称 的本地化字符串。
        /// </summary>
        public static string PleaseInputAxisName {
            get {
                return ResourceManager.GetString("PleaseInputAxisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择通信方式 的本地化字符串。
        /// </summary>
        public static string PleaseSelectCommType {
            get {
                return ResourceManager.GetString("PleaseSelectCommType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位 的本地化字符串。
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位运动前提 的本地化字符串。
        /// </summary>
        public static string PosionMotionPremise {
            get {
                return ResourceManager.GetString("PosionMotionPremise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置(mm) 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位参数配置 的本地化字符串。
        /// </summary>
        public static string PositionParameterConfig {
            get {
                return ResourceManager.GetString("PositionParameterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置(pulse) 的本地化字符串。
        /// </summary>
        public static string PositionPulse {
            get {
                return ResourceManager.GetString("PositionPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推压距离 的本地化字符串。
        /// </summary>
        public static string PressDistance {
            get {
                return ResourceManager.GetString("PressDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力曲线 的本地化字符串。
        /// </summary>
        public static string PressDriver {
            get {
                return ResourceManager.GetString("PressDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推压值(N) 的本地化字符串。
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机 的本地化字符串。
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用进度 的本地化字符串。
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议 的本地化字符串。
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉冲比计算 的本地化字符串。
        /// </summary>
        public static string PulseCal {
            get {
                return ResourceManager.GetString("PulseCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到位脉冲 的本地化字符串。
        /// </summary>
        public static string PulseCount {
            get {
                return ResourceManager.GetString("PulseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉冲比 的本地化字符串。
        /// </summary>
        public static string PulseRatio {
            get {
                return ResourceManager.GetString("PulseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出脉宽 的本地化字符串。
        /// </summary>
        public static string PulseWidth {
            get {
                return ResourceManager.GetString("PulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出赋值 的本地化字符串。
        /// </summary>
        public static string PutValue {
            get {
                return ResourceManager.GetString("PutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量读取 的本地化字符串。
        /// </summary>
        public static string ReadAll {
            get {
                return ResourceManager.GetString("ReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据 的本地化字符串。
        /// </summary>
        public static string ReadData {
            get {
                return ResourceManager.GetString("ReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否只读 的本地化字符串。
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读写类型 的本地化字符串。
        /// </summary>
        public static string ReadOrWrite {
            get {
                return ResourceManager.GetString("ReadOrWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对运动 的本地化字符串。
        /// </summary>
        public static string RelativeMove {
            get {
                return ResourceManager.GetString("RelativeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回 的本地化字符串。
        /// </summary>
        public static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回检知 的本地化字符串。
        /// </summary>
        public static string RetractDetetor {
            get {
                return ResourceManager.GetString("RetractDetetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回DI 的本地化字符串。
        /// </summary>
        public static string RetractDI {
            get {
                return ResourceManager.GetString("RetractDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回DO 的本地化字符串。
        /// </summary>
        public static string RetractDO {
            get {
                return ResourceManager.GetString("RetractDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回名称 的本地化字符串。
        /// </summary>
        public static string RetractName {
            get {
                return ResourceManager.GetString("RetractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回状态 的本地化字符串。
        /// </summary>
        public static string RetractStatus {
            get {
                return ResourceManager.GetString("RetractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人 的本地化字符串。
        /// </summary>
        public static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人名称 的本地化字符串。
        /// </summary>
        public static string RobotName {
            get {
                return ResourceManager.GetString("RobotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人运动模式 的本地化字符串。
        /// </summary>
        public static string RobotRunModel {
            get {
                return ResourceManager.GetString("RobotRunModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人运动模式选择 的本地化字符串。
        /// </summary>
        public static string RobotRunModelTip {
            get {
                return ResourceManager.GetString("RobotRunModelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI高度 的本地化字符串。
        /// </summary>
        public static string ROIHeight {
            get {
                return ResourceManager.GetString("ROIHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI开始X 的本地化字符串。
        /// </summary>
        public static string ROIStartX {
            get {
                return ResourceManager.GetString("ROIStartX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI开始Y 的本地化字符串。
        /// </summary>
        public static string ROIStartY {
            get {
                return ResourceManager.GetString("ROIStartY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI宽度 的本地化字符串。
        /// </summary>
        public static string ROIWidth {
            get {
                return ResourceManager.GetString("ROIWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行速度 的本地化字符串。
        /// </summary>
        public static string RunSpeed {
            get {
                return ResourceManager.GetString("RunSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全设备 的本地化字符串。
        /// </summary>
        public static string SafeDevice {
            get {
                return ResourceManager.GetString("SafeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全门 的本地化字符串。
        /// </summary>
        public static string SafeDoor {
            get {
                return ResourceManager.GetString("SafeDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴2 的本地化字符串。
        /// </summary>
        public static string SecondAxis {
            get {
                return ResourceManager.GetString("SecondAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二个 IO 的本地化字符串。
        /// </summary>
        public static string SecondIO {
            get {
                return ResourceManager.GetString("SecondIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择运动轴 的本地化字符串。
        /// </summary>
        public static string SelectAxis {
            get {
                return ResourceManager.GetString("SelectAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择厂商 的本地化字符串。
        /// </summary>
        public static string SelectBrand {
            get {
                return ResourceManager.GetString("SelectBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择编码器 的本地化字符串。
        /// </summary>
        public static string SelectEncoderTip {
            get {
                return ResourceManager.GetString("SelectEncoderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择Excel文件 的本地化字符串。
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择当前激光配置 的本地化字符串。
        /// </summary>
        public static string SelectLaserConfigutation {
            get {
                return ResourceManager.GetString("SelectLaserConfigutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择线扫配置文件地址 的本地化字符串。
        /// </summary>
        public static string SelectLaserConfigutationPath {
            get {
                return ResourceManager.GetString("SelectLaserConfigutationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择运动控制卡 的本地化字符串。
        /// </summary>
        public static string SelectMotinCard {
            get {
                return ResourceManager.GetString("SelectMotinCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择离线图片 的本地化字符串。
        /// </summary>
        public static string SelectOfflineImage {
            get {
                return ResourceManager.GetString("SelectOfflineImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择离线点云 的本地化字符串。
        /// </summary>
        public static string SelectOfflinePointCloud {
            get {
                return ResourceManager.GetString("SelectOfflinePointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择对应的安全设备 的本地化字符串。
        /// </summary>
        public static string SelectSafeDevice {
            get {
                return ResourceManager.GetString("SelectSafeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送报文 的本地化字符串。
        /// </summary>
        public static string SendPacket {
            get {
                return ResourceManager.GetString("SendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号 的本地化字符串。
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第七个 IO 的本地化字符串。
        /// </summary>
        public static string SeventhIO {
            get {
                return ResourceManager.GetString("SeventhIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏蔽设备 的本地化字符串。
        /// </summary>
        public static string ShieldDevice {
            get {
                return ResourceManager.GetString("ShieldDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图 的本地化字符串。
        /// </summary>
        public static string Shot {
            get {
                return ResourceManager.GetString("Shot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示点云 的本地化字符串。
        /// </summary>
        public static string ShowPointCloud {
            get {
                return ResourceManager.GetString("ShowPointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟赋值 的本地化字符串。
        /// </summary>
        public static string SimulationValue {
            get {
                return ResourceManager.GetString("SimulationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单控 的本地化字符串。
        /// </summary>
        public static string SingleControl {
            get {
                return ResourceManager.GetString("SingleControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第六个 IO 的本地化字符串。
        /// </summary>
        public static string SixthIO {
            get {
                return ResourceManager.GetString("SixthIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从站名称 的本地化字符串。
        /// </summary>
        public static string SlaveName {
            get {
                return ResourceManager.GetString("SlaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从站号 的本地化字符串。
        /// </summary>
        public static string SlaveNo {
            get {
                return ResourceManager.GetString("SlaveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC插槽 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket类型 的本地化字符串。
        /// </summary>
        public static string SocketType {
            get {
                return ResourceManager.GetString("SocketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度(mm) 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度系数 的本地化字符串。
        /// </summary>
        public static string SpeedCoefficient {
            get {
                return ResourceManager.GetString("SpeedCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实速度=速度 * 系数 的本地化字符串。
        /// </summary>
        public static string SpeedTip {
            get {
                return ResourceManager.GetString("SpeedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始地址 的本地化字符串。
        /// </summary>
        public static string StartAddress {
            get {
                return ResourceManager.GetString("StartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始点检 的本地化字符串。
        /// </summary>
        public static string StartCheck {
            get {
                return ResourceManager.GetString("StartCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始编号 的本地化字符串。
        /// </summary>
        public static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始IO 的本地化字符串。
        /// </summary>
        public static string StartIO {
            get {
                return ResourceManager.GetString("StartIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始触发 的本地化字符串。
        /// </summary>
        public static string StartTrigger {
            get {
                return ResourceManager.GetString("StartTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 的本地化字符串。
        /// </summary>
        public static string StationNO {
            get {
                return ResourceManager.GetString("StationNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位 的本地化字符串。
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子定义 的本地化字符串。
        /// </summary>
        public static string SubDefinite {
            get {
                return ResourceManager.GetString("SubDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸 的本地化字符串。
        /// </summary>
        public static string Suck {
            get {
                return ResourceManager.GetString("Suck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸DO 的本地化字符串。
        /// </summary>
        public static string SuckDO {
            get {
                return ResourceManager.GetString("SuckDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签高度 的本地化字符串。
        /// </summary>
        public static string TagHeight {
            get {
                return ResourceManager.GetString("TagHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签宽度 的本地化字符串。
        /// </summary>
        public static string TagWidth {
            get {
                return ResourceManager.GetString("TagWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰科统计 的本地化字符串。
        /// </summary>
        public static string TaikeContent {
            get {
                return ResourceManager.GetString("TaikeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰科曲线 的本地化字符串。
        /// </summary>
        public static string TaikeCurve {
            get {
                return ResourceManager.GetString("TaikeCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示教 的本地化字符串。
        /// </summary>
        public static string Teach {
            get {
                return ResourceManager.GetString("Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴3 的本地化字符串。
        /// </summary>
        public static string ThirdAxis {
            get {
                return ResourceManager.GetString("ThirdAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三个 IO 的本地化字符串。
        /// </summary>
        public static string ThirdIO {
            get {
                return ResourceManager.GetString("ThirdIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发次数 的本地化字符串。
        /// </summary>
        public static string TriggerCount {
            get {
                return ResourceManager.GetString("TriggerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发Fifo数量 的本地化字符串。
        /// </summary>
        public static string TriggerFifoCount {
            get {
                return ResourceManager.GetString("TriggerFifoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发输出通道 的本地化字符串。
        /// </summary>
        public static string TriggerNo {
            get {
                return ResourceManager.GetString("TriggerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发输出通道计数 的本地化字符串。
        /// </summary>
        public static string TriggerNoCount {
            get {
                return ResourceManager.GetString("TriggerNoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发通道类型 的本地化字符串。
        /// </summary>
        public static string TriggerNoType {
            get {
                return ResourceManager.GetString("TriggerNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发脉冲百分比 的本地化字符串。
        /// </summary>
        public static string TriggerPluseRatio {
            get {
                return ResourceManager.GetString("TriggerPluseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Txt 的本地化字符串。
        /// </summary>
        public static string TxtReader {
            get {
                return ResourceManager.GetString("TxtReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未监控设备(双击添加监控) 的本地化字符串。
        /// </summary>
        public static string UnMonitorDevice {
            get {
                return ResourceManager.GetString("UnMonitorDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上使能 的本地化字符串。
        /// </summary>
        public static string UppperEnable {
            get {
                return ResourceManager.GetString("UppperEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB口 的本地化字符串。
        /// </summary>
        public static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用 的本地化字符串。
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真空检知 的本地化字符串。
        /// </summary>
        public static string VacuumSensor {
            get {
                return ResourceManager.GetString("VacuumSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真空检知DI 的本地化字符串。
        /// </summary>
        public static string VacuumSensorDI {
            get {
                return ResourceManager.GetString("VacuumSensorDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置值 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真轴 的本地化字符串。
        /// </summary>
        public static string VAxis {
            get {
                return ResourceManager.GetString("VAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真轴3 的本地化字符串。
        /// </summary>
        public static string VAxis3 {
            get {
                return ResourceManager.GetString("VAxis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴列表(双击显示) 的本地化字符串。
        /// </summary>
        public static string VAxisIOAxisListTip {
            get {
                return ResourceManager.GetString("VAxisIOAxisListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴列表(双击添加) 的本地化字符串。
        /// </summary>
        public static string VAxisListTip {
            get {
                return ResourceManager.GetString("VAxisListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真多轴 的本地化字符串。
        /// </summary>
        public static string VAxisM {
            get {
                return ResourceManager.GetString("VAxisM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真皮带 的本地化字符串。
        /// </summary>
        public static string VBelt {
            get {
                return ResourceManager.GetString("VBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真相机 的本地化字符串。
        /// </summary>
        public static string VCamera {
            get {
                return ResourceManager.GetString("VCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真通信 的本地化字符串。
        /// </summary>
        public static string VCommuncation {
            get {
                return ResourceManager.GetString("VCommuncation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真气缸 的本地化字符串。
        /// </summary>
        public static string VCylinder {
            get {
                return ResourceManager.GetString("VCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚拟设备 的本地化字符串。
        /// </summary>
        public static string VDevice {
            get {
                return ResourceManager.GetString("VDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真电批 的本地化字符串。
        /// </summary>
        public static string VESD {
            get {
                return ResourceManager.GetString("VESD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真飞达 的本地化字符串。
        /// </summary>
        public static string VFeeder {
            get {
                return ResourceManager.GetString("VFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真飞拍 的本地化字符串。
        /// </summary>
        public static string VFlyingPhoto {
            get {
                return ResourceManager.GetString("VFlyingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真输入 的本地化字符串。
        /// </summary>
        public static string VInputIO {
            get {
                return ResourceManager.GetString("VInputIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真IO 的本地化字符串。
        /// </summary>
        public static string VIO {
            get {
                return ResourceManager.GetString("VIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO仿真设备 的本地化字符串。
        /// </summary>
        public static string VIOSimulation {
            get {
                return ResourceManager.GetString("VIOSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vision过程参数 的本地化字符串。
        /// </summary>
        public static string VisionProcessData {
            get {
                return ResourceManager.GetString("VisionProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真线激光 的本地化字符串。
        /// </summary>
        public static string VLineLaser {
            get {
                return ResourceManager.GetString("VLineLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真电缸 的本地化字符串。
        /// </summary>
        public static string VMCylinder {
            get {
                return ResourceManager.GetString("VMCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真输出 的本地化字符串。
        /// </summary>
        public static string VOutputIO {
            get {
                return ResourceManager.GetString("VOutputIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力矩电缸 的本地化字符串。
        /// </summary>
        public static string VPCylinder {
            get {
                return ResourceManager.GetString("VPCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真PLC 的本地化字符串。
        /// </summary>
        public static string VPlc {
            get {
                return ResourceManager.GetString("VPlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真打印机 的本地化字符串。
        /// </summary>
        public static string VPrinter {
            get {
                return ResourceManager.GetString("VPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真机器人 的本地化字符串。
        /// </summary>
        public static string VRobot {
            get {
                return ResourceManager.GetString("VRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真SerialPort 的本地化字符串。
        /// </summary>
        public static string VSerialPort {
            get {
                return ResourceManager.GetString("VSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真Socket 的本地化字符串。
        /// </summary>
        public static string VSocket {
            get {
                return ResourceManager.GetString("VSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真三色灯 的本地化字符串。
        /// </summary>
        public static string VTricolorlamp {
            get {
                return ResourceManager.GetString("VTricolorlamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真真空 的本地化字符串。
        /// </summary>
        public static string VVacuum {
            get {
                return ResourceManager.GetString("VVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据 的本地化字符串。
        /// </summary>
        public static string WriteData {
            get {
                return ResourceManager.GetString("WriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入报文 的本地化字符串。
        /// </summary>
        public static string WritePacket {
            get {
                return ResourceManager.GetString("WritePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入值 的本地化字符串。
        /// </summary>
        public static string WriteValue {
            get {
                return ResourceManager.GetString("WriteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鑫精诚 的本地化字符串。
        /// </summary>
        public static string XJCPressureSensor {
            get {
                return ResourceManager.GetString("XJCPressureSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零点偏移 的本地化字符串。
        /// </summary>
        public static string ZeroOffset {
            get {
                return ResourceManager.GetString("ZeroOffset", resourceCulture);
            }
        }
    }
}
