<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Luster.Module.Motion.AOI.Core\Luster.Module.Motion.AOI.Core.csproj" />
    <ProjectReference Include="..\..\src\Modules\Luster.TaskFlow.Motion\Luster.TaskFlow.Motion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>