<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Luster.Common.DataStruct\Luster.Common.DataStruct.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MinVer" />
    </ItemGroup>

</Project>
