<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<AssemblyName>DC.Authorization</AssemblyName>
	</PropertyGroup>

	<!-- 纯接口+模型项目：零第三方依赖 -->

</Project>

