<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Modules\Luster.SimDevice.Light\Luster.SimDevice.Light.csproj" />
		<ProjectReference Include="..\..\Modules\Luster.TaskFlow.Motion\Luster.TaskFlow.Motion.csproj" />
	</ItemGroup>

</Project>
