<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Luster.XamlLinter</RootNamespace>
    <AssemblyName>Luster.XamlLinter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
