<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
        <!-- 启用统一拷贝功能:DLL 拷贝到 Motions/ 目录由主程序动态加载 -->
        <CopyToMotionsFolder>true</CopyToMotionsFolder>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Luster.TaskFlow.Motion\Luster.TaskFlow.Motion.csproj" />
	</ItemGroup>

    <ItemGroup>
        <PackageReference Include="MinVer" />
    </ItemGroup>

	<ItemGroup>
	  <Reference Include="System.ComponentModel.DataAnnotations" />
	</ItemGroup>

</Project>
